services:
  tool-registry:
    build: .

    environment:
      TOOL_REGISTRY_DATABASE__HOST: ${TOOL_REGISTRY_DATABASE__HOST}
      TOOL_REGISTRY_DATABASE__PORT: ${TOOL_REGISTRY_DATABASE__PORT}
      TOOL_REGISTRY_DATABASE__NAME: ${TOOL_REGISTRY_DATABASE__NAME}
      TOOL_REGISTRY_DATABASE__USER: ${TOOL_REGISTRY_DATABASE__USER}
      TOOL_REGISTRY_DATABASE__PASSWORD: ${TOOL_REGISTRY_DATABASE__PASSWORD}

