[logging]
log_file = "@format {env[BASE_DIR]}/logs/tool-registry.log"
log_level = "INFO"
use_detailed_format = false

[database]
host = "localhost"
port = 5432
name = "toolsdb"
user = "harvester"
password = "yourpassword"

[service]
name = "Tool Registry"
listen_port = 8181
bind_address = "127.0.0.1"
api_prefix = "/api/v1"
admin_auth_key = "changeme"
egi_env = "production" # Set to "production" or "development" or "demo"

